### ISSUE TITLE
1.20.1fabric服务器玩家进服崩溃

### ISSUE THREAD

**Issue by HansOffice** [TartaricAcid/ysm#101]
使用的模组版本为yesstevemodel-1.20-fabric-1.1.5-hotfix-2-minified
服务端版本为fabric 1.20.1
fabric加载器版本0.15.9
fabric Api版本为[API]fabric-api-0.92.1+1.20.1
崩溃日志：
[latest.log](https://github.com/TartaricAcid/ysm/files/15108130/latest.log)
崩溃前输出[18:18:45] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoSuchFieldError: OooOo0oOoOO0o00OO000oO00
	at com.elfmcys.yesstevemodel.OoOoOOO00OoOo00oooOoo00.<clinit>(Unknown Source) ~[%5B����%5D%5Bʷ�ٷ�%5Dyesstevemodel-1.20-fabric-release-1.1.5-hotfix-2.jar:?]
	at net.minecraft.class_1657.OooOo0oOoOO0o00OO000oO00(class_1657.java:18388) ~[server-intermediary.jar:?]
	at com.elfmcys.yesstevemodel.OoOOOoO0ooo0oO000O0o0O.OooOo0oOoOO0o00OO000oO00(Unknown Source) ~[%5B����%5D%5Bʷ�ٷ�%5Dyesstevemodel-1.20-fabric-release-1.1.5-hotfix-2.jar:?]
	at com.elfmcys.yesstevemodel.ooOoO0OOooO00oOo00oooOoo.OooOo0oOoOO0o00OO000oO00(Unknown Source) ~[%5B����%5D%5Bʷ�ٷ�%5Dyesstevemodel-1.20-fabric-release-1.1.5-hotfix-2.jar:?]
	at com.elfmcys.yesstevemodel.Ooo00OOoOO0oOOoO000o0oo0.OooOo0oOoOO0o00OO000oO00(Unknown Source) ~[%5B����%5D%5Bʷ�ٷ�%5Dyesstevemodel-1.20-fabric-release-1.1.5-hotfix-2.jar:?]
	at net.fabricmc.fabric.api.networking.v1.ServerPlayConnectionEvents.lambda$static$2(ServerPlayConnectionEvents.java:48) ~[fabric-networking-api-v1-1.3.11+1802ada577-cf20906c7ecece00.jar:?]
	at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.onClientReady(ServerPlayNetworkAddon.java:66) ~[fabric-networking-api-v1-1.3.11+1802ada577-cf20906c7ecece00.jar:?]
	at net.minecraft.class_3324.handler$ddi001$fabric-networking-api-v1$handlePlayerConnection(class_3324.java:7463) ~[server-intermediary.jar:?]
	at net.minecraft.class_3324.method_14570(class_3324.java:215) ~[server-intermediary.jar:?]
	at net.minecraft.class_3248.method_33800(class_3248.java:131) ~[server-intermediary.jar:?]
	at net.minecraft.class_3248.method_14384(class_3248.java:632) ~[server-intermediary.jar:?]
	at net.minecraft.class_3248.redirect$ddj000$fabric-networking-api-v1$handlePlayerJoin(class_3248.java:1063) ~[server-intermediary.jar:?]
	at net.minecraft.class_3248.method_18784(class_3248.java:68) ~[server-intermediary.jar:?]
	at net.minecraft.class_2535.method_10754(class_2535.java:259) ~[server-intermediary.jar:?]
	at net.minecraft.class_3242.method_14357(class_3242.java:172) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:908) ~[server-intermediary.jar:?]
	at net.minecraft.class_3176.method_3813(class_3176.java:283) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:2111) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by ABlueDogLazy** [comment]
ubuntu 在docker中部署服务器添加模组也会有这个错误，玩家一加入服务器就会崩溃

**Comment by Asukaaa648** [comment]
同样的问题，在群晖里面原生运行的

**Comment by TartaricAcid** [comment]
Fix in 2.2.1
