### ISSUE TITLE
Fabric2.2.1版本与插件Luckperms，PlaceholderAPI不兼容

### ISSUE THREAD

**Issue by Haitangan** [TartaricAcid/ysm#123]
1.20.1的Banner混合端，服务端加入此模组后，插件Luckperms和PlaceholderAPI无法正常加载
![屏幕截图 2024-07-10 234701](https://github.com/TartaricAcid/ysm/assets/107090333/bae43325-01e9-4eeb-ab1c-7a648ba2bed9)

服务段报错：
Error occurred while enabling LuckPerms v5.4.137 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at me.lucko.luckperms.lib.adventure.platform.bukkit.CraftBukkitFacet$Chat1_19_3.isSupported(CraftBukkitFacet.java:309) ~[?:?]
        at me.lucko.luckperms.lib.adventure.platform.facet.Facet.of(Facet.java:79) ~[?:?]
        at me.lucko.luckperms.lib.adventure.platform.bukkit.BukkitAudience.<clinit>(BukkitAudience.java:44) ~[?:?]
        at me.lucko.luckperms.lib.adventure.platform.bukkit.BukkitAudiencesImpl.createAudience(BukkitAudiencesImpl.java:132) ~[?:?]
        at me.lucko.luckperms.lib.adventure.platform.bukkit.BukkitAudiencesImpl.createAudience(BukkitAudiencesImpl.java:74) ~[?:?]
        at me.lucko.luckperms.lib.adventure.platform.facet.FacetAudienceProvider.lambda$addViewer$0(FacetAudienceProvider.java:112) ~[?:?]
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1710) ~[?:?]
        at me.lucko.luckperms.lib.adventure.platform.facet.FacetAudienceProvider.addViewer(FacetAudienceProvider.java:110) ~[?:?]
        at me.lucko.luckperms.lib.adventure.platform.bukkit.BukkitAudiencesImpl.<init>(BukkitAudiencesImpl.java:99) ~[?:?]
        at me.lucko.luckperms.lib.adventure.platform.bukkit.BukkitAudiencesImpl$Builder.lambda$build$1(BukkitAudiencesImpl.java:171) ~[?:?]
        at java.util.HashMap.computeIfAbsent(HashMap.java:1228) ~[?:?]
        at java.util.Collections$SynchronizedMap.computeIfAbsent(Collections.java:2981) ~[?:?]
        at me.lucko.luckperms.lib.adventure.platform.bukkit.BukkitAudiencesImpl$Builder.build(BukkitAudiencesImpl.java:169) ~[?:?]
        at me.lucko.luckperms.lib.adventure.platform.bukkit.BukkitAudiencesImpl.instanceFor(BukkitAudiencesImpl.java:89) ~[?:?]
        at me.lucko.luckperms.lib.adventure.platform.bukkit.BukkitAudiences.create(BukkitAudiences.java:53) ~[?:?]
        at me.lucko.luckperms.bukkit.BukkitSenderFactory.<init>(BukkitSenderFactory.java:45) ~[?:?]
        at me.lucko.luckperms.bukkit.LPBukkitPlugin.setupSenderFactory(LPBukkitPlugin.java:113) ~[?:?]
        at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:137) ~[?:?]
        at me.lucko.luckperms.bukkit.LPBukkitBootstrap.onEnable(LPBukkitBootstrap.java:175) ~[?:?]
        at me.lucko.luckperms.bukkit.loader.BukkitLoaderPlugin.onEnable(BukkitLoaderPlugin.java:50) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:267) ~[banner-1.20.1-655.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) ~[banner-1.20.1-655.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:482) ~[banner-1.20.1-655.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:537) ~[banner-1.20.1-655.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:459) ~[banner-1.20.1-655.jar:?]
        at net.minecraft.class_3176.handler$zkn001$banner$initServer(class_3176.java:687) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3823(class_3176.java:166) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:2061) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:1570) ~[?:?]
Caused by: java.lang.RuntimeException: Cannot load class com.elfmcys.yesstevemodel.oo0O0OOoo0000oOo0OOo0O0o in environment type SERVER
        at net.fabricmc.loader.impl.transformer.FabricTransformer.transform(FabricTransformer.java:59) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPreMixinClassByteArray(KnotClassDelegate.java:462) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:415) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.11.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:529) ~[?:?]
        at java.lang.Class.forName(Class.java:508) ~[?:?]
        at sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:113) ~[?:?]
        at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:125) ~[?:?]
        at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49) ~[?:?]
        at sun.reflect.generics.visitor.Reifier.reifyTypeArguments(Reifier.java:68) ~[?:?]
        at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:138) ~[?:?]
        at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49) ~[?:?]
        at sun.reflect.generics.repository.MethodRepository.computeReturnType(MethodRepository.java:75) ~[?:?]
        at sun.reflect.generics.repository.MethodRepository.getReturnType(MethodRepository.java:66) ~[?:?]
        at java.lang.reflect.Method.getGenericReturnType(Method.java:299) ~[?:?]
        at com.mohistmc.banner.bukkit.remapping.ClassLoaderRemapper.checkMethodTypes(ClassLoaderRemapper.java:167) ~[banner-1.20.1-655.jar:?]
        at com.mohistmc.banner.bukkit.remapping.ClassLoaderRemapper.tryGetMethods(ClassLoaderRemapper.java:110) ~[banner-1.20.1-655.jar:?]
        at com.mohistmc.banner.bukkit.remapping.ClassLoaderRemapper.lambda$getMethods$0(ClassLoaderRemapper.java:102) ~[banner-1.20.1-655.jar:?]
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1742) ~[?:?]
        at com.mohistmc.banner.bukkit.remapping.ClassLoaderRemapper.getMethods(ClassLoaderRemapper.java:102) ~[banner-1.20.1-655.jar:?]
        at com.mohistmc.banner.bukkit.remapping.ClassLoaderRemapper.tryMapMethodToSrg(ClassLoaderRemapper.java:223) ~[banner-1.20.1-655.jar:?]
        at com.mohistmc.banner.bukkit.remapping.ReflectionHandler_1.handleLookupFindStatic(ReflectionHandler.java:304) ~[banner-1.20.1-655.jar:?]
        at com.mohistmc.banner.bukkit.remapping.ReflectionHandler_1.handleLookupFindVirtual(ReflectionHandler.java:320) ~[banner-1.20.1-655.jar:?]
        at me.lucko.luckperms.lib.adventure.platform.bukkit.MinecraftReflection.searchMethod(MinecraftReflection.java:182) ~[?:?]
        at me.lucko.luckperms.lib.adventure.platform.bukkit.MinecraftReflection.searchMethod(MinecraftReflection.java:157) ~[?:?]
        at me.lucko.luckperms.lib.adventure.platform.bukkit.CraftBukkitAccess$Chat1_19_3.<clinit>(CraftBukkitAccess.java:95) ~[?:?]
        ... 30 more

设备信息：
Minecraft Version: 1.20.1
Minecraft Version ID: 1.20.1
Operating System: Windows 11 (amd64) version 10.0
Java Version: 22.0.1, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
Memory: 174040776 bytes (165 MiB) / 555745280 bytes (530 MiB) up to 2147483648 bytes (2048 MiB)
CPUs: 32

**Comment by MiskaDaeve** [comment]
Do not use banner as it's unstable and ysm are defining some classes of itself while starting up
