### ISSUE TITLE
[Feature Request] Linux 客户端支持

### ISSUE THREAD

**Issue by XiYang6666** [TartaricAcid/ysm#153]
Linux 客户端无法使用该模组

测试平台: Manjaro 24.1.0
内核版本: x86_64 Linux 6.10.11-2
报错信息:
```
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 2024-10-07 10:43:07
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'yes_steve_model' at 'com.elfmcys.yesstevemodel.YesSteveModel'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:458)
	at net.minecraft.client.main.Main.main(Main.java:211)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.RuntimeException: Only YSM server is supported on linux.
	at com.elfmcys.yesstevemodel.o0OO00OoO000OoO0oo0OooOo.O0000oO0oo000000OoooO0oO(Unknown Source)
	at com.elfmcys.yesstevemodel.o0OO00OoO000OoO0oo0OooOo.oO000Oo00OOo0OoO0ooooooo(Unknown Source)
	at com.elfmcys.yesstevemodel.oOOo0OoO00Oooo0OOoOooOOO.oO000Oo00OOo0OoO0ooooooo(Unknown Source)
	at com.elfmcys.yesstevemodel.YesSteveModel.onInitialize(Unknown Source)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399)
	... 6 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:458)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:211)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Linux (amd64) version 6.10.11-2-MANJARO
	Java Version: 21.0.4, Arch Linux
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Arch Linux
	Memory: 54474704 bytes (51 MiB) / 352321536 bytes (336 MiB) up to 8342470656 bytes (7956 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: 13th Gen Intel(R) Core(TM) i5-13500H
	Identifier: Intel64 Family 6 Model 186 Stepping 2
	Microarchitecture: unknown
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 12
	Number of logical CPUs: 16
	Graphics card #0 name: Raptor Lake-P [Iris Xe Graphics]
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 256.00
	Graphics card #0 deviceId: 0xa7a0
	Graphics card #0 versionInfo: unknown
	Graphics card #1 name: AD107M [GeForce RTX 4050 Max-Q / Mobile]
	Graphics card #1 vendor: NVIDIA Corporation (0x10de)
	Graphics card #1 VRAM (MB): 8224.00
	Graphics card #1 deviceId: 0x28e1
	Graphics card #1 versionInfo: unknown
	Virtual memory max (MB): 15910.46
	Virtual memory used (MB): 7106.92
	Swap memory total (MB): 0.00
	Swap memory used (MB): 0.00
	JVM Flags: 0 total; 
	Fabric Mods: 
		fabric-api: Fabric API 0.92.2+1.20.1
			fabric-api-base: Fabric API Base 0.4.31+1802ada577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.36+1802ada577
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.13+1802ada577
			fabric-block-api-v1: Fabric Block API (v1) 1.0.11+1802ada577
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.1+1802ada577
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.41+1802ada577
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.2+1802ada577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.34+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.13+1802ada577
			fabric-commands-v0: Fabric Commands (v0) 0.2.51+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.64+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.11+1802ada577
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.5+1802ada577
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.19+1802ada577
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.0.0+de0fd6d177
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.4+1802ada577
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.54+1802ada577
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.0+1c78457f77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.2+1802ada577
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.63+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.40+1802ada577
			fabric-item-api-v1: Fabric Item API (v1) 2.1.28+1802ada577
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.12+1802ada577
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.37+1802ada577
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.35+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.22+1802ada577
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.1+1802ada577
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.45+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.9+1802ada577
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.50+1802ada577
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.3+1802ada577
			fabric-models-v0: Fabric Models (v0) 0.4.2+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.11+1802ada577
			fabric-networking-v0: Fabric Networking (v0) 0.3.51+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.3+1802ada577
			fabric-particles-v1: Fabric Particles (v1) 1.1.2+1802ada577
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.21+1802ada577
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.3+1802ada577
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.1+1802ada577
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.2+85287f9f77
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.46+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.37+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.28+1802ada577
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.49+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.8+1802ada577
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.8+1802ada577
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.10+1802ada577
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.8+1802ada577
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.30+1802ada577
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.13+1802ada577
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.5+8dd72ea377
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.1+1802ada577
		fabricloader: Fabric Loader 0.16.5
			mixinextras: MixinExtras 0.4.1
		java: OpenJDK 64-Bit Server VM 21
		minecraft: Minecraft 1.20.1
		yes_steve_model: Yes Steve Model 2.2.2
			forgeconfigapiport: Forge Config API Port 8.0.0
	Launched Version: 1.20.1-fabric0.16.5
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>
```

**Comment by TartaricAcid** [comment]
Linux 客户端的 API 经常变动，而且由于开发者的现实原因，我们缺乏时间和技术能力来完成相关 API 的兼容适配

**Comment by TartaricAcid** [comment]
目前正常进行中，相关进度后续会发布

**Comment by KAE-Ame** [comment]
At the same time, the old version of the mod 1.1.5 runs perfect on linux. Why did you forbid running on linux? This is the first time I see a mod that specifically refuses to run because of the operating system. Why?

**Comment by TartaricAcid** [comment]
First of all, let me correct one of your mistakes. We do not **forbid** the mod from running on Linux.

Because the old version was cracked and resold, we used C++ for the new version. As we all know, C++ is a difficult cross-platform language (people who know the reason why Java was born should know this), so we are still adapting the Linux client (the server can run normally)

On the other hand, I don’t understand why you use the word "**forbid**". YSM is just a hobby project. It is a mod we developed in our spare time. For us, time cost is very important

**Comment by KAE-Ame** [comment]
Ok, thank you

**Comment by TartaricAcid** [comment]
If we have any progress on the Linux client, we will announce it. Please wait patiently.

There is another problem that I have found to be very common recently. I don’t know what is going on.
Some people use some **very extreme words** when it comes to system adaptation.

I personally think that this is nothing more than the inability to adapt due to time and energy, which is understandable behavior. But your words make me feel that I am deliberately hostile to players of a certain operating system (even if the actual situation is not the case at all).

This reminds me of a very interesting saying: 
> If there is no quarrel, you can create quarrels

**Comment by MrHua269** [comment]
看看你都说的什么
https://github.com/MiskaDaeve/AboutYsm/releases/tag/1

**Comment by astro-angelfish** [comment]
请问还有Linux支持的进展嘛.-.

我在这半年的期间中没有搜到任何有关进展，是否存在一些困难需要帮助

**Comment by TartaricAcid** [comment]
2.5.2 已经发布，支持 Linux 客户端运行，此问题关闭
