### ISSUE TITLE
1.20.1服务端玩家链接服务器时出现错误的玩家数据错误

### ISSUE THREAD

**Issue by Jiangsubei** [TartaricAcid/ysm#53]
报错如下：
[04:24:16] [Server thread/ERROR]: Couldn't place player in world
net.minecraft.class_148: Loading entity NBT
        at net.minecraft.class_1297.method_5651(class_1297.java:1939) ~[server-intermediary.jar:?]
        at net.minecraft.class_29.method_261(class_29.java:54) ~[server-intermediary.jar:?]
        at net.minecraft.class_3324.method_14600(class_3324.java:378) ~[server-intermediary.jar:?]
        at net.minecraft.class_3324.method_14570(class_3324.java:164) ~[server-intermediary.jar:?]
        at net.minecraft.class_3248.method_33800(class_3248.java:131) ~[server-intermediary.jar:?]
        at net.minecraft.class_3248.method_14384(class_3248.java:118) ~[server-intermediary.jar:?]
        at net.minecraft.class_3248.redirect$zic000$fabric-networking-api-v1$handlePlayerJoin(class_3248.java:563) ~[server-intermediary.jar
:?]
        at net.minecraft.class_3248.method_18784(class_3248.java:68) ~[server-intermediary.jar:?]
        at net.minecraft.class_2535.method_10754(class_2535.java:259) ~[server-intermediary.jar:?]
        at net.minecraft.class_3242.method_14357(class_3242.java:172) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:908) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3813(class_3176.java:283) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:1623) ~[?:?]
Caused by: java.lang.NoSuchFieldError: OooOo0oOoOO0o00OO000oO00
        at com.elfmcys.yesstevemodel.OoOoOOO00OoOo00oooOoo00.<clinit>(Unknown Source) ~[yesstevemodel-1.20-fabric-release-1.1.5-hotfix-2.jar
:?]
        at net.minecraft.class_1657.OooOo0oOoOO0o00OO000oO00(class_1657.java:5888) ~[server-intermediary.jar:?]
        at net.minecraft.class_1657.handler$zpl000$yes_steve_model$OooOo0oOoOO0o00OO000oO00(class_1657.java:5895) ~[server-intermediary.jar:
?]
        at net.minecraft.class_1657.method_5749(class_1657.java:846) ~[server-intermediary.jar:?]
        at net.minecraft.class_3222.method_5749(class_3222.java:327) ~[server-intermediary.jar:?]
        at net.minecraft.class_1297.method_5651(class_1297.java:1930) ~[server-intermediary.jar:?]
        ... 15 more

服务端和客户端都已正常安装前置和mod。使用mod版本：1.20-1.1.5-hotfix-2

**Comment by gggngnjng** [comment]
我服也遇到了这个bug，版本1.19.2，服务器报错日志显示如下：
[17:36:56 INFO]: com.mojang.authlib.GameProfile@b4730c6[id=XXXXX,name=XXXXX,properties={},legacy=false] (/1145141919810) lost connection: Invalid player data
[17:36:56 WARN]: handleDisconnection() called twice
[17:37:15 ERROR]: Couldn't place player in world
net.minecraft.class_148: Loading entity NBT
	at net.minecraft.class_1297.method_5651(class_1297.java:1815) ~[server-intermediary.jar:?]
	at net.minecraft.class_29.method_261(class_29.java:56) ~[server-intermediary.jar:?]
	at net.minecraft.class_3324.method_14600(class_3324.java:360) ~[server-intermediary.jar:?]
	at net.minecraft.class_3324.method_14570(class_3324.java:151) ~[server-intermediary.jar:?]
	at net.minecraft.class_3248.method_33800(class_3248.java:151) ~[server-intermediary.jar:?]
	at net.minecraft.class_3248.method_14384(class_3248.java:138) ~[server-intermediary.jar:?]
	at net.minecraft.class_3248.redirect$zfe000$fabric-networking-api-v1$handlePlayerJoin(class_3248.java:1063) ~[server-intermediary.jar:?]
	at net.minecraft.class_3248.method_18784(class_3248.java:73) ~[server-intermediary.jar:?]
	at net.minecraft.class_2535.method_10754(class_2535.java:248) ~[server-intermediary.jar:?]
	at net.minecraft.class_3242.method_14357(class_3242.java:183) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:886) ~[server-intermediary.jar:?]
	at net.minecraft.class_3176.method_3813(class_3176.java:289) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.elfmcys.yesstevemodel.OoOoOOO00OoOo00oooOoo00
	at net.minecraft.class_1657.OooOo0oOoOO0o00OO000oO00(class_1657.java:3869) ~[server-intermediary.jar:?]
	at net.minecraft.class_1657.handler$znb000$yes_steve_model$OooOo0oOoOO0o00OO000oO00(class_1657.java:3876) ~[server-intermediary.jar:?]
	at net.minecraft.class_1657.method_5749(class_1657.java:867) ~[server-intermediary.jar:?]
	at net.minecraft.class_3222.method_5749(class_3222.java:316) ~[server-intermediary.jar:?]
	at net.minecraft.class_1297.method_5651(class_1297.java:1806) ~[server-intermediary.jar:?]
	... 15 more
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoSuchFieldError: Class com.elfmcys.yesstevemodel.OoOoOOO00OoOo00oooOoo00 does not have member field 'java.util.Map OooOo0oOoOO0o00OO000oO00' [in thread "Server thread"]
	at com.elfmcys.yesstevemodel.OoOoOOO00OoOo00oooOoo00.<clinit>(Unknown Source) ~[yesstevemodel-1.19.2-fabric-release-1.1.5-hotfix-2%20(1).jar:?]
	at net.minecraft.class_1657.OooOo0oOoOO0o00OO000oO00(class_1657.java:3869) ~[server-intermediary.jar:?]
	at net.minecraft.class_1657.handler$znb000$yes_steve_model$OooOo0oOoOO0o00OO000oO00(class_1657.java:3876) ~[server-intermediary.jar:?]
	at net.minecraft.class_1657.method_5749(class_1657.java:867) ~[server-intermediary.jar:?]
	at net.minecraft.class_3222.method_5749(class_3222.java:316) ~[server-intermediary.jar:?]
	at net.minecraft.class_1297.method_5651(class_1297.java:1806) ~[server-intermediary.jar:?]
	... 15 more
其中XXXXX分别代表UUID与玩家游戏名，1145141919810代表我的ip地址
客户端报错日志如下：
[18:10:43] [Netty Client IO #1/INFO]: Connected to a modded server.
请开发者注意

**Comment by tang-bai** [comment]
出现一样问题服务器版本为1.20.1 Fabric 0.15.7 模组版本yesstevemodel-1.20-fabric-release-1.1.5-hotfix-2
[02:08:26] [Server thread/INFO]: tang__bai[/127.0.0.1:3225] logged in with entity id 454 at (-7.5, 217.0, -2.5)
[02:08:27] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoSuchFieldError: OooOo0oOoOO0o00OO000oO00
	at com.elfmcys.yesstevemodel.OoOoOOO00OoOo00oooOoo00.<clinit>(Unknown Source) ~[%5B是，史蒂夫模型%5D%20yesstevemodel-1.20-fabric-release-1.1.5-hotfix-2.jar:?]
	at net.minecraft.class_1657.OooOo0oOoOO0o00OO000oO00(class_1657.java:12388) ~[server-intermediary.jar:?]
	at com.elfmcys.yesstevemodel.OoOOOoO0ooo0oO000O0o0O.OooOo0oOoOO0o00OO000oO00(Unknown Source) ~[%5B是，史蒂夫模型%5D%20yesstevemodel-1.20-fabric-release-1.1.5-hotfix-2.jar:?]
	at com.elfmcys.yesstevemodel.ooOoO0OOooO00oOo00oooOoo.OooOo0oOoOO0o00OO000oO00(Unknown Source) ~[%5B是，史蒂夫模型%5D%20yesstevemodel-1.20-fabric-release-1.1.5-hotfix-2.jar:?]
	at com.elfmcys.yesstevemodel.Ooo00OOoOO0oOOoO000o0oo0.OooOo0oOoOO0o00OO000oO00(Unknown Source) ~[%5B是，史蒂夫模型%5D%20yesstevemodel-1.20-fabric-release-1.1.5-hotfix-2.jar:?]
	at net.fabricmc.fabric.api.networking.v1.ServerPlayConnectionEvents.lambda$static$2(ServerPlayConnectionEvents.java:48) ~[fabric-networking-api-v1-1.3.11+1802ada577-4657550f9c265bf4.jar:?]
	at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.onClientReady(ServerPlayNetworkAddon.java:66) ~[fabric-networking-api-v1-1.3.11+1802ada577-4657550f9c265bf4.jar:?]
	at net.minecraft.class_3324.handler$beb000$fabric-networking-api-v1$handlePlayerConnection(class_3324.java:5018) ~[server-intermediary.jar:?]
	at net.minecraft.class_3324.method_14570(class_3324.java:215) ~[server-intermediary.jar:?]
	at net.minecraft.class_3248.method_33800(class_3248.java:131) ~[server-intermediary.jar:?]
	at net.minecraft.class_3248.method_14384(class_3248.java:118) ~[server-intermediary.jar:?]
	at net.minecraft.class_3248.redirect$bec000$fabric-networking-api-v1$handlePlayerJoin(class_3248.java:563) ~[server-intermediary.jar:?]
	at net.minecraft.class_3248.method_18784(class_3248.java:68) ~[server-intermediary.jar:?]
	at net.minecraft.class_2535.method_10754(class_2535.java:259) ~[server-intermediary.jar:?]
	at net.minecraft.class_3242.method_14357(class_3242.java:172) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:908) ~[server-intermediary.jar:?]
	at net.minecraft.class_3176.method_3813(class_3176.java:283) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.handler$zif000$carpet$modifiedRunLoop(MinecraftServer.java:6442) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:650) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[02:08:27] [Server thread/ERROR]: This crash report has been saved to: D:\新建文件夹 (2)\新建文件夹 (3)\.\crash-reports\crash-2024-03-31_02.08.27-server.txt

**Comment by TartaricAcid** [comment]
Fix in 2.2.1
