### ISSUE TITLE
[Bug?]1.18.2情况下出现大量刷写错误日志（未崩溃且mod运行良好）

### ISSUE THREAD

**Issue by Sorrow-Scarlet** [TartaricAcid/ysm#64]
# 问题
- 日志**大量刷写**如下内容：

[17Feb2024 19:39:50.749] [Thread-71/ERROR] [yes_steve_model/]: Failed to parse value eyelib.add_glow()
com.elfmcys.yesstevemodel.O0O0oO0o0Oo00oOoOoo0oO0O: Failed to get property: eyelib
  at line 0, column 6
	at com.elfmcys.yesstevemodel.Oo00Oo00ooOo0o0oOoO0o0OO.OooOo0oOoOO0o00OO000oO00(Unknown Source) ~[?:1.2.0]
	at com.elfmcys.yesstevemodel.Oo00Oo00ooOo0o0oOoO0o0OO.OooOo0oOoOO0o00OO000oO00(Unknown Source) ~[?:1.2.0]
	at com.elfmcys.yesstevemodel.Oo00Oo00ooOo0o0oOoO0o0OO.oOOoO0Oo0oo0O0OO00OoO0Oo(Unknown Source) ~[?:1.2.0]
	at com.elfmcys.yesstevemodel.Oo00Oo00ooOo0o0oOoO0o0OO.oooooOo0oO0oo0oo0oOOoOOo(Unknown Source) ~[?:1.2.0]
	at com.elfmcys.yesstevemodel.O0ooo0o000OOOOOo0O0O0oO0.ooOoO0OOooO00oOo00oooOoo(Unknown Source) ~[yesstevemodel-forge-1.18.2-1.2.0.jar%23263!/:1.2.0]
	at com.elfmcys.yesstevemodel.o0O00O0o00oooOOo00OooOo.OooOo0oOoOO0o00OO000oO00(Unknown Source) ~[yesstevemodel-forge-1.18.2-1.2.0.jar%23263!/:1.2.0]
	at com.elfmcys.yesstevemodel.OOoOOo00O0OoO0OOOoOo000.OooOo0oOoOO0o00OO000oO00(Unknown Source) ~[yesstevemodel-forge-1.18.2-1.2.0.jar%23263!/:1.2.0]
	at com.elfmcys.yesstevemodel.OooO0OO000O0ooO00O0oO0O0.OoOOOoO0ooo0oO000O0o0O(Unknown Source) ~[yesstevemodel-forge-1.18.2-1.2.0.jar%23263!/:1.2.0]
	at com.elfmcys.yesstevemodel.OooO0OO000O0ooO00O0oO0O0.OooOo0oOoOO0o00OO000oO00(Unknown Source) [yesstevemodel-forge-1.18.2-1.2.0.jar%23263!/:1.2.0]

# 吐槽
我怀着颤抖的心，点开了报告，试图找到一个和ysm不相关的报错，滚动条轻轻一拉，看到了一大串ysm的Oo00OooO,求我的心理阴影面积....

# LOG
[latest.log](https://github.com/TartaricAcid/ysm/files/14318636/latest.log)

# 额外提醒
- LOG后面有个illegal packet连接中断，应该和ysm无关，请忽略。
- 使用Embeddium等优化mod，无oculus。

**Comment by Sorrow-Scarlet** [comment]
# 额外吐槽
非常坏的log,使我的大脑 O-oooooooooo AAAAE-A-A-I-A-U- JO-oooooooooooo AAE-O-A-A-U-U-A- E-eee-ee-eee AAAAE-A-E-I-E-A- JO-ooo-oo-oo-oo EEEEO-A-AAA-AAAA

**Comment by TomatoPuddin** [comment]
这是某些模型动画的 molang 有错误或用了不支持的特性导致解析失败，一般不影响游玩

**Comment by Sorrow-Scarlet** [comment]
好的，就是这个log为啥会刷Ooo0oo0O啊，看着好怪233（

**Comment by PopSlime** [comment]
> 好的，就是这个log为啥会刷Ooo0oo0O啊，看着好怪233（

鉴定为代码混淆器。这个是用来混淆 mod 文件里的符号的，使得 mod 被反编译之后不能通过符号的名称快速地读懂程序的逻辑，起到一定的保护作用。

**Comment by TomatoPuddin** [comment]
下版本会改善这种情况

**Comment by Sorrow-Scarlet** [comment]
> > 好的，就是这个log为啥会刷Ooo0oo0O啊，看着好怪233（
> 
> 鉴定为代码混淆器。这个是用来混淆 mod 文件里的符号的，使得 mod 被反编译之后不能通过符号的名称快速地读懂程序的逻辑，起到一定的保护作用。

好的，了解到了
